### ISSUE TITLE
Error when running bash scripts/train.sh —-config baseline.yml

### ISSUE THREAD

**Issue by xiami2019** [NLP-Playground/LaSS#3]
`usage: train.py [-h] [--config CONFIG] [--force-reset]
train.py: error: unrecognized arguments: —-config ./configs/demo/baseline.yml --train-script-path /remote-home/qycheng/anaconda3/envs/LaSS/bin/fairseq-train`
It seems that trian.py doesn't have the arguement --train-script-path.

**Comment by linzehui** [comment]
fixed
