### ISSUE TITLE
关于验证

### ISSUE THREAD

**Issue by shaoyangxu** [NLP-Playground/LaSS#4]
作者您好，问一个不太重要的问题：
我在[这里](https://github.com/NLP-Playground/LaSS/blob/83be1881e9c25e26b598401d73867170af5adeba/fairseq_code/toolbox/generate_from_config.py#L24)看见默认用的checkpoint是完整训练的最后一个checkpoint，所以想请教作者一下，一般在模型测试的时候，使用的是最好的那一个checkpoint还是最后一个？

**Comment by linzehui** [comment]
一般是best

**Comment by shaoyangxu** [comment]
好的谢谢，没别的问题（
